project:
  type: book
  output-dir: ../docs
  pre-render:
    - ../neo4j.sh status neo4j.json
    - make images
  render:
    - "!*.md"

filters:
 - include-code-files

metadata-files:
  - neo4j.json

book:
  title: "NFDI4Objects Knowledge Graph (TA5)"
  subtitle: "Technisches Handbuch für Management und Nutzung"
  repo-url: https://github.com/nfdi4objects/n4o-graph
  language: de
  repo-subdir: manual
  repo-actions:
    - source
  chapters:
    - index.qmd
    - basics.qmd
    - usage.qmd
    - cypher.qmd
    - sparql.qmd
    - sources.qmd
    - schema.qmd
    - architecture.qmd
  page-footer: 
    right: 
      - text: Datenschutz
        href: https://www.gbv.de/datenschutz
      - text: Impressum
        href: https://www.gbv.de/impressum
      - icon: github
        href: https://github.com/nfdi4objects/n4o-graph

tbl-cap-location: bottom
number-sections: false
number-depth: 1

format:
  html:
    theme: cosmo
    link-external-icon: true
    syntax-definitions:
     - pg.xml
    include-before-body:
      text: |
        <script src="./js/codemirror.js"></script>
        <script src="./js/cypher.js"></script>
        <script src="./js/sparql.js"></script>
        <script src="./js/turtle.js"></script>
        <script src="./js/runmode.js"></script>
        <script src="./js/highlight.js"></script>
    css:
      - codemirror.css

